/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.tdmsl.app.ventanas;

import java.awt.*;
import javax.swing.*;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author Manu
 */
public class CutePaste extends javax.swing.JDialog {

    /**
     * Creates new form CutePaste
     */
    public CutePaste(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Manuel Dafauce
    private void initComponents() {
        BotonCortar = new javax.swing.JButton(new DefaultEditorKit.CutAction());
        BotonCopiar = new javax.swing.JButton(new DefaultEditorKit.CopyAction());
        BotonPegar = new javax.swing.JButton(new DefaultEditorKit.PasteAction());

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new Dimension(200, 75));
        Container contentPane = getContentPane();
        contentPane.setLayout(new FlowLayout());

        //---- BotonCortar ----
        BotonCortar.setIcon(new ImageIcon(getClass().getResource("/es/tdmsl/app/images/cortar.gif")));
        BotonCortar.setToolTipText("Cortar");
        BotonCortar.addActionListener(e -> BotonCortarActionPerformed(e));
        contentPane.add(BotonCortar);

        //---- BotonCopiar ----
        BotonCopiar.setIcon(new ImageIcon(getClass().getResource("/es/tdmsl/app/images/copiar.gif")));
        BotonCopiar.setToolTipText("Copiar");
        BotonCopiar.addActionListener(e -> BotonCopiarActionPerformed(e));
        contentPane.add(BotonCopiar);

        //---- BotonPegar ----
        BotonPegar.setIcon(new ImageIcon(getClass().getResource("/es/tdmsl/app/images/pegar.gif")));
        BotonPegar.setToolTipText("Pegar");
        BotonPegar.addActionListener(e -> BotonPegarActionPerformed(e));
        contentPane.add(BotonPegar);
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCortarActionPerformed
        dispose();
    }//GEN-LAST:event_BotonCortarActionPerformed

    private void BotonCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCopiarActionPerformed
        dispose();
    }//GEN-LAST:event_BotonCopiarActionPerformed

    private void BotonPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPegarActionPerformed
       dispose();
    }//GEN-LAST:event_BotonPegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CutePaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CutePaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CutePaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CutePaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CutePaste dialog = new CutePaste(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Manuel Dafauce
    private JButton BotonCortar;
    private JButton BotonCopiar;
    private JButton BotonPegar;
    // End of variables declaration//GEN-END:variables
}
